config/routes.rb
Rails.application.routes.draw do
  resources :album_reviews
  resources :albums
  resources :photo_reviews
  resources :photos
  resources :book_reviews
  get 'users/show'
  root 'static_pages#home'

  devise_for :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :photo
    belongs_to :user
    has_many :album_review, -> { order "created_at DESC"}
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @id = @album.id
    puts @id
    @photos = Photo.where("album_id = ?" , @id)
    @album_review = AlbumReview.new
  end

  # GET /albums/new
  def new
    @album = current_user.albums.build
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:user_id, :name)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <!--<div class="field">-->
  <!--  <%= form.label :review %>-->
  <!--  <%= form.text_area :review %>-->
  <!--</div>-->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>
<style>
#index-view-image img {
  border-radius: 10px;
  border-style: solid;
  border-width: 1px;
  max-width: 100px;
  max-height: 100px;
}
</style>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <!--<th>Review</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>
  <% if @albums %>
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td><%= album.user.name %></td>
          <td><%= album.name %></td>
          <!--<td><%= album.review %></td>-->
          <td><%= link_to 'Show', album %></td>
          <td><%= link_to 'Edit', edit_album_path(album) %></td>
          <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<style>
#index-view-image img {
  border-radius: 10px;
  border-style: solid;
  border-width: 1px;
  max-width: 100px;
  max-height: 100px;
}
</style>
<button><%= link_to 'Add Photo', new_photo_path %></button>
<p>
  <strong>User:</strong>
  <%= @album.user.name %>
</p>
<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Date</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td>
          <span id="index-view-image"><%= image_tag(photo.image) %></span>
        </td>
        <td><%= photo.title %></span></td>
        <td><%= photo.date %></td>
        <td><%= photo.detail %></td>
      </tr>
      <tr>
        <td>
          <button><%= link_to 'Show', photo %></button>
          <button><%= link_to 'Edit', edit_photo_path(photo) %></button>
          <button><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--<p>-->
<!--  <strong>Review:</strong>-->
<!--  <%= @album.review %>-->
<!--</p>-->
<h2>Review From</h2>
 <%= form_with(model: @album_review, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :review %>
     <%= form.hidden_field :album_id, :value => @album.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>
 
  <h2>Review List</h2>
     <ul>
       <% @album.album_review.each do |album_review|%>
        <li><%= album_review.review %>
          (<i><%= album_review.user.name%></i>)
        </li>

     <% end %>
     </ul>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>