config/routes.rb
Rails.application.routes.draw do
  resources :album_reviews
  resources :albums
  resources :photo_reviews
  resources :photos
  resources :book_reviews
  get 'users/show'
  root 'static_pages#home'

  devise_for :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one_attached :image
    has_many :photo_review, -> { order "created_at DESC" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo_review = PhotoReview.new
  end
  # GET /photos/new
  def new
    @photo = Photo.new
    @album = Album.all.map{ |alb| [alb.id] }
  end

  # GET /photos/1/edit
  def edit
     @album = Album.all.map{ |alb| [alb.id] }
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.album_id = params[:album_id]

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    puts "this is #{params}"
    @photo.album_id =params[:album_id]
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:title, :date, :image, :detail, :album_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "upload-image" %>
  </div>
  
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div class="field">
    <%= form.label :album_name %>
    <%= select_tag :album_id, options_for_select(@album), prompt: "Select Album", class: 'form-control select2' %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<style>
#index-view-image img {
  border-radius: 10px;
  border-style: solid;
  border-width: 1px;
  max-width: 100px;
  max-height: 100px;
}
</style>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Date</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td>
          <span id="index-view-image"><%= image_tag(photo.image) %></span>
        </td>
        <td><%= photo.title %></span></td>
        <td><%= photo.date %></td>
        <td><%= photo.detail %></td>
      </tr>
      <tr>
        <td>
          <button><%= link_to 'Show', photo %></button>
          <button><%= link_to 'Edit', edit_photo_path(photo) %></button>
          <button><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Photo', new_photo_path %></button>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<style>
#show-image img {
  max-width: 500px;
}
</style>

<p id="notice"><%= notice %></p>

<p>
  <h2><%= @photo.title %></h2>
</p>

<p>     
    <span id="show-image"> <%= image_tag @photo.image %></span>
 </p>
 
 <p>
  <strong>Date:</strong>
  <%= @photo.date %>
</p>

<p>
  <strong>Detail</strong>
  <br />
  <textarea disabled style="resize: none; border-radius: 5px; width: 300px; min-height: 100px"><%= @photo.detail %></textarea>
</p>

<h2>Review</h2>
<%= form_with(model: @photo_review, local: true) do |form| %>
  <div class= "field">
    <%= form.text_area :review %>
    <%= form.hidden_field :photo_id, :value => @photo.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 
<h2>Review List</h2>
     <ul>
       <% @photo.photo_review.each do |photo_review|%>
        <li><%= photo_review.review %>
          (<b><%= photo_review.user.name %></b>)</li>
     <% end %>
     </ul>
 
<button><%= link_to 'Edit', edit_photo_path(@photo) %></button> |
<button><%= link_to 'Back', photos_path %></button>