config/routes.rb
Rails.application.routes.draw do
  resources :album_reviews
  resources :albums
  resources :photo_reviews
  resources :photos
  resources :book_reviews
  get 'users/show'
  root 'static_pages#home'

  devise_for :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
end

app/controllers/photo_reviews_controller.rb
class PhotoReviewsController < ApplicationController
  before_action :set_photo_review, only: [:show, :edit, :update, :destroy]

  # GET /photo_reviews
  # GET /photo_reviews.json
  def index
    @photo_reviews = PhotoReview.all
  end

  # GET /photo_reviews/1
  # GET /photo_reviews/1.json
  def show
  end

  # GET /photo_reviews/new
  def new
    @photo_review = PhotoReview.new
  end

  # GET /photo_reviews/1/edit
  def edit
  end

  # POST /photo_reviews
  # POST /photo_reviews.json
  def create
    @photo_review = PhotoReview.new(photo_review_params)
    @photo_review.user_id = current_user.id

    respond_to do |format|
      if @photo_review.save
        url = "/photos/" + @photo_review.photo_id.to_s 
        format.html { redirect_to url, notice: 'Photo review was successfully created.' }
        format.json { render :show, status: :created, location: @photo_review }
      else
        format.html { render :new }
        format.json { render json: @photo_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_reviews/1
  # PATCH/PUT /photo_reviews/1.json
  def update
    respond_to do |format|
      if @photo_review.update(photo_review_params)
        format.html { redirect_to @photo_review, notice: 'Photo review was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_review }
      else
        format.html { render :edit }
        format.json { render json: @photo_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_reviews/1
  # DELETE /photo_reviews/1.json
  def destroy
    @photo_review.destroy
    respond_to do |format|
      format.html { redirect_to photo_reviews_url, notice: 'Photo review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_review
      @photo_review = PhotoReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_review_params
      params.require(:photo_review).permit(:user_id, :photo_id, :review)
    end
end

app/helpers/photo_reviews_helper.rb
module PhotoReviewsHelper
end

app/views/photo_reviews/_form.html.erb
<%= form_with(model: photo_review, local: true) do |form| %>
  <% if photo_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_review.errors.count, "error") %> prohibited this photo_review from being saved:</h2>

      <ul>
        <% photo_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :photo_id %>
    <%= form.number_field :photo_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_reviews/edit.html.erb
<h1>Editing Photo Review</h1>

<%= render 'form', photo_review: @photo_review %>

<%= link_to 'Show', @photo_review %> |
<%= link_to 'Back', photo_reviews_path %>

app/views/photo_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photo Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Photo</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_reviews.each do |photo_review| %>
      <tr>
        <td><%= photo_review.user_id %></td>
        <td><%= photo_review.photo_id %></td>
        <td><%= photo_review.review %></td>
        <td><%= link_to 'Show', photo_review %></td>
        <td><%= link_to 'Edit', edit_photo_review_path(photo_review) %></td>
        <td><%= link_to 'Destroy', photo_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo Review', new_photo_review_path %>

app/views/photo_reviews/new.html.erb
<h1>New Photo Review</h1>

<%= render 'form', photo_review: @photo_review %>

<%= link_to 'Back', photo_reviews_path %>

app/views/photo_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @photo_review.user_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @photo_review.photo_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @photo_review.review %>
</p>

<%= link_to 'Edit', edit_photo_review_path(@photo_review) %> |
<%= link_to 'Back', photo_reviews_path %>